version: '3.9'

services:
  db:
    #image: postgres:13
    image: ghcr.io/songjaewon7361/postgres:13
    environment:
      POSTGRES_DB: todolist
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      #PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata

  web:
    #build: .
    image: ghcr.io/songjaewon7361/prjdocker-web:latest
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=todolist
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

volumes:
  postgres_data:
